
baseURL = "https://jukejeew.github.io/stickers-uncle-pub/"
title = "Sticker Portfolio"
languageCode = "th"
defaultContentLanguage = "th"
# theme = ""
enableGitInfo = false
canonifyURLs = true

enableRobotsTXT = true

[params]
siteName = "Sticker Portfolio"
disableKinds = ["taxonomy", "taxonomyTerm"]
